name: "Composite Action Test"
description: "Run multiple run steps"

runs:
  using: "composite"
  steps: 
    - run: chmod +x $GITHUB_ACTION_PATH/test/script2.sh
      shell: sh
    - run: chmod +x $GITHUB_ACTION_PATH/script.sh
      shell: sh
    - run: $GITHUB_ACTION_PATH/test/script2.sh
      shell: sh
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
