name: "Composite Action Test"
description: "Run multiple run steps"

runs:
  using: "composite"
  steps: 
    - run: echo ${{ github.action_path }}/test/script2.sh
    - run: chmod +x ${{ github.action_path }}/test/script2.sh
    - run: echo $TEST_ENV
      env: 
        TEST_ENV: ${{ toJson(env) }}
    - run: chmod +x ${{ env.GITHUB_ACTION_PATH }}/script.sh
    - run: ${{ env.GITHUB_ACTION_PATH }}/script.sh
    - run: ${{ github.action_path }}/test/script2.sh
