name: "Composite Action Test"
description: "Run multiple run steps"

runs:
  using: "composite"
  steps: 
    - run: printenv
    - run: echo ${{ github.action_path }}/test/script2.sh
    - run: chmod +x ${{ github.action_path }}/test/script2.sh
    - run: chmod +x ${{ GITHUB_ACTION_PATH }}/script.sh
    - run: ${{ GITHUB_ACTION_PATH }}/script.sh
    - run: ${{ github.action_path }}/test/script2.sh
